### ISSUE TITLE
a thought on null end times

### ISSUE THREAD

**Issue by fscottfoti** [CityofSantaMonica/mds-provider-services#42]
FWIW, [this](https://github.com/CityofSantaMonica/mds-provider-services/blob/master/analytics/query.py#L153) line seems especially unforgiving to data errors where trips don't end properly or service_end events aren't sent.  Basically it would treat any data error that preceded the time in question as if the vehicle is still out there.  Alternatively this clause could also be limited to start_time's in the last 7 days or something along those lines.  Just a thought.  I think it's fine as it is, but it just seemed worth flagging since it's something that might come up again in the future at some point.

**Comment by thekaveman** [comment]
Thank you for your thoughts on this @fscottfoti.

The line in question is deliberate. [Since `active_windows` are Trip based](https://github.com/CityofSantaMonica/mds-provider-services/blob/master/db/availability/active_windows.sql#L16), rather than Status Change based, this is irrelevant to the case when a data error occurs for Status Changes indicating start/end of trips. We always have a closed `active_window`.

In the case of an open Status Change based `inactive_window` - there is no way for us to distinguish between a data error, a device that is truly still in the PROW, lost by the company, etc. As such, we will continue to look at `inactive_windows` that are not closed, and continue to assume this means that the device is in the PROW.

The issue with applying some limited range on `start_time` (in your example, 7 days prior) is that the calculation methodology must in fact be the same and work for long and short periods of time. We should be able to (and do) run the calculation on an hourly, daily, weekly, monthly, and other random (e.g. January 1- January 20) time periods.

We only [ingest valid MDS data](https://github.com/CityofSantaMonica/mds-provider-services/blob/master/ingest/validate.py#L28) and calculate based on the valid data we receive. Providers are responsible for ensuring their data feeds are accurate and complete.

Hard-coding some notion of "we haven't heard from this vehicle in X time, so it must be gone from the PROW" is simply out of the question.
