### ISSUE TITLE
How do we get a status change if the vehicle has been moved?

### ISSUE THREAD

**Issue by patata3000** [CityofSantaMonica/mds-provider-services#58]
I wish there were a way to know that a vehicle has been moved outside of a trip in the provider API. Maybe there is but I don't know how it translates in the API.
To give an example: if a random user just takes a vehicle and moves it 100 meters from the end of the last placement (end of a trip, agency_drop_off, rebalance_drop_off...), I believe the provider should say that the vehicle was moved.

**Comment by thekaveman** [comment]
@patata3000 - the situation you describe is not currently handled under the MDS Provider API. The API captures "official" movement of the devices, e.g. movement due to company operational actions (deploy, pickup) or user trip (start/end) actions.

That being said, it is theoretically possible to analyze status change and trip data for spatial differences between e.g. the reported deployment location and the location of the first trip start (or subsequent pick-up location). If these two events do not occur roughly in the same location, it can be inferred that the device was moved in some "non-official" way (e.g. the random person picking it up and moving it without actually using it).

**Comment by patata3000** [comment]
Are you planning to implement that ?

**Comment by thekaveman** [comment]
I do not have any plans to implement that at this time. Happy to accept a PR or talk through more details though.

**Comment by patata3000** [comment]
So I don't know which repo to contribute to. For mds-provider-services, should I go to the one in CityOfLosAngeles? To exchange ideas on mds spec, I imagine I should go to https://github.com/CityOfLosAngeles/mobility-data-specification.
If we were to talk about implementing handling of unofficial movement, shouldn't it be in the mobility-data-specification repo. Or you just want to implement it the way you described it in your previous message?

**Comment by thekaveman** [comment]
The spec itself lives at the repo you linked to: https://github.com/CityOfLosAngeles/mobility-data-specification. If you are suggesting something like additional status_change [`event_types`](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/master/provider#event-types) or a new/refined interpretation of the language of the spec, that would be the repo to make those suggestions in.

This repository is a wrapper and additional tooling around [`mds-provider`](/CityofSantaMonica/mds-provider), a Python library implementing the Provider API and data ingestion capabilities from a *consumer's* perspective (e.g. a City or Transit Agency). If you are suggesting a new analytical method, a new way of ingesting or interpreting the data - this repository (`mds-provider-services`) is probably the one you want to target. I'm not totally clear on the end goal, but one suggestion might be a new SQL view that produces a list of devices that were moved "unofficially" based on criteria you outline.

Does this make sense?

**Comment by patata3000** [comment]
Yes it does. Thanks :)
