### ISSUE TITLE
status_changes_sequence_id_idx : sequence_id does not exist

### ISSUE THREAD

**Issue by patata3000** [CityofSantaMonica/mds-provider-services#59]
In `db/setup/status_changes.sql`, there is an index creation of an unexisting column (sequence_id).
This column exists in trips. I don't know if there should be a column named sequence_id in status_changes as well (whatever it is) or if the index should simply not be created.

**Comment by thekaveman** [comment]
@patata3000 - you are absolutely correct, that column was omitted unintentionally. I added the fix in 86c421c9, part of a suite of changes for MDS 0.3.x support that is pending release. 

If you would like to get the fix sooner, feel free to submit a PR against `master` with the same change and I can get it merged ASAP. Otherwise, #56 will be merged *soonish* (I have a big backlog of other things going on, but it feels ready to go... if you'd like to test out the work in that branch and submit any issues of problems you find, that would be immensely helpful as well!)

**Comment by patata3000** [comment]
If it's just a matter of adding a line, I can do it

**Comment by patata3000** [comment]
https://github.com/CityofSantaMonica/mds-provider-services/pull/60

**Comment by thekaveman** [comment]
Thanks for that, I merged!
